[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#B95E3D"
backgroundColor = "#F5F2EE"
secondaryBackgroundColor = "#FFFDFA"
textColor = "#292D2A"
font = "sans serif"
